### ISSUE TITLE
Copy dependencies with server type to tomcatDir/shared/lib for local deployment 

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba-gradle-plugin#141]
### Environment

- Platform version: 7.2
### Description of the bug or enhancement
- Minimal reproducible example
Server dependencies are copied to the server libs (`tomcatDir/lib` dir) instead of shared libs (`tomcatDir/shared/lib` dir). Sometimes this configuration leads to errors when server libs depend from shared lib.
A possible solution might be copying server type dependencies into shared libs.

**Comment by soraksh** [comment]
QA: check that `server` type dependincies now copied to `tomcatDir/shared/lib` dir instead of `tomcatDir/lib` dir by deploying to local tomcat.
For example, add `logstash` dependency as `server` dependency (see [original issue](https://github.com/cuba-platform/cuba-gradle-plugin/issues/126)):
```
configure(globalModule) {
    dependencies {
        server('net.logstash.logback:logstash-logback-encoder:6.3')
       ...
    }
}
```
And then check if application actually works with by adding it to logback file:
