### ISSUE TITLE
Extract cuba-front to a separate project 

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba-gradle-plugin#84]
It is updated rarely. There is no need to release it every platform release

Relates to cuba-platform/cuba#1175

**Comment by clumsym76** [comment]
In former version was it possible to overwrite the frontProject in task buildUberJar by usage of  **polymerProject**

The documentation still contains 
`polymerProject - a Gradle project representing the Polymer UI module. If not defined, the standard polymer-client module is used.`
please see at https://doc.cuba-platform.com/manual-7.0/build.gradle_buildUberJar.html

I guess it is missing due to a merge conflict.

Is it possible to reenable it soon?

**Comment by andreysubbotin** [comment]
See cuba-platform/cuba-gradle-plugin/issues/96#issuecomment-465898811
